bumps:
  points:
  - - - 1
      - 1
    - - 0
      - 1
  - - - 1
      - 1
    - - 1
      - 0
  - - - 1
      - 98
    - - 1
      - 99
  - - - 1
      - 98
    - - 0
      - 98
  - - - 98
      - 99
    - - 98
      - 98
  - - - 99
      - 98
    - - 98
      - 98
