bumps:
  points:
  - - - 3
      - 0
    - - 3
      - 1
  - - - 4
      - 0
    - - 4
      - 1
  - - - 4
      - 1
    - - 4
      - 2
  - - - 5
      - 1
    - - 5
      - 2
  - - - 5
      - 2
    - - 5
      - 3
  - - - 5
      - 3
    - - 5
      - 4
  - - - 2
      - 1
    - - 3
      - 1
  - - - 3
      - 1
    - - 4
      - 1
  - - - 4
      - 2
    - - 5
      - 2
  - - - 4
      - 3
    - - 5
      - 3
  - - - 1
      - 4
    - - 2
      - 4
  - - - 2
      - 4
    - - 3
      - 4
  - - - 3
      - 4
    - - 4
      - 4
  - - - 2
      - 4
    - - 2
      - 5
  - - - 3
      - 3
    - - 3
      - 4
  - - - 3
      - 4
    - - 3
      - 5
  weight: 30