bumps:
  points:
  - - - 1
      - 1
    - - 0
      - 1
  - - - 1
      - 1
    - - 1
      - 0
  - - - 1
      - 18
    - - 1
      - 19
  - - - 1
      - 18
    - - 0
      - 18
  - - - 18
      - 1
    - - 18
      - 0
  - - - 19
      - 1
    - - 18
      - 1
  - - - 18
      - 19
    - - 18
      - 18
  - - - 19
      - 18
    - - 18
      - 18
