blocks:
- - - 2
    - 0
  - - 2
    - 1
- - - 3
    - 0
  - - 3
    - 1
- - - 4
    - 0
  - - 4
    - 1
- - - 5
    - 0
  - - 5
    - 1
- - - 6
    - 0
  - - 6
    - 1
- - - 7
    - 0
  - - 7
    - 1
- - - 8
    - 0
  - - 8
    - 1
- - - 9
    - 0
  - - 9
    - 1
- - - 10
    - 0
  - - 10
    - 1
- - - 11
    - 0
  - - 11
    - 1
- - - 12
    - 0
  - - 12
    - 1
- - - 13
    - 0
  - - 13
    - 1
- - - 14
    - 0
  - - 14
    - 1
- - - 15
    - 0
  - - 15
    - 1
- - - 16
    - 0
  - - 16
    - 1
- - - 17
    - 0
  - - 17
    - 1
- - - 19
    - 2
  - - 18
    - 2
- - - 19
    - 3
  - - 18
    - 3
- - - 19
    - 4
  - - 18
    - 4
- - - 19
    - 5
  - - 18
    - 5
- - - 19
    - 6
  - - 18
    - 6
- - - 19
    - 7
  - - 18
    - 7
- - - 19
    - 8
  - - 18
    - 8
- - - 19
    - 9
  - - 18
    - 9
- - - 19
    - 10
  - - 18
    - 10
- - - 19
    - 11
  - - 18
    - 11
- - - 19
    - 12
  - - 18
    - 12
- - - 19
    - 13
  - - 18
    - 13
- - - 19
    - 14
  - - 18
    - 14
- - - 19
    - 15
  - - 18
    - 15
- - - 19
    - 16
  - - 18
    - 16
- - - 19
    - 17
  - - 18
    - 17
- - - 2
    - 19
  - - 2
    - 18
- - - 3
    - 19
  - - 3
    - 18
- - - 4
    - 19
  - - 4
    - 18
- - - 5
    - 19
  - - 5
    - 18
- - - 6
    - 19
  - - 6
    - 18
- - - 7
    - 19
  - - 7
    - 18
- - - 8
    - 19
  - - 8
    - 18
- - - 9
    - 19
  - - 9
    - 18
- - - 10
    - 19
  - - 10
    - 18
- - - 11
    - 19
  - - 11
    - 18
- - - 12
    - 19
  - - 12
    - 18
- - - 13
    - 19
  - - 13
    - 18
- - - 14
    - 19
  - - 14
    - 18
- - - 15
    - 19
  - - 15
    - 18
- - - 16
    - 19
  - - 16
    - 18
- - - 17
    - 19
  - - 17
    - 18
- - - 0
    - 2
  - - 1
    - 2
- - - 0
    - 3
  - - 1
    - 3
- - - 0
    - 4
  - - 1
    - 4
- - - 0
    - 5
  - - 1
    - 5
- - - 0
    - 6
  - - 1
    - 6
- - - 0
    - 7
  - - 1
    - 7
- - - 0
    - 8
  - - 1
    - 8
- - - 0
    - 9
  - - 1
    - 9
- - - 0
    - 10
  - - 1
    - 10
- - - 0
    - 11
  - - 1
    - 11
- - - 0
    - 12
  - - 1
    - 12
- - - 0
    - 13
  - - 1
    - 13
- - - 0
    - 14
  - - 1
    - 14
- - - 0
    - 15
  - - 1
    - 15
- - - 0
    - 16
  - - 1
    - 16
- - - 0
    - 17
  - - 1
    - 17
- - - 1
    - 2
  - - 1
    - 1
- - - 1
    - 4
  - - 1
    - 3
- - - 1
    - 6
  - - 1
    - 5
- - - 1
    - 9
  - - 1
    - 8
- - - 1
    - 10
  - - 0
    - 10
- - - 1
    - 11
  - - 1
    - 10
- - - 1
    - 14
  - - 0
    - 14
- - - 1
    - 15
  - - 0
    - 15
- - - 1
    - 16
  - - 1
    - 15
- - - 2
    - 1
  - - 2
    - 0
- - - 2
    - 6
  - - 1
    - 6
- - - 2
    - 8
  - - 2
    - 7
- - - 2
    - 9
  - - 1
    - 9
- - - 2
    - 10
  - - 2
    - 9
- - - 2
    - 12
  - - 1
    - 12
- - - 2
    - 14
  - - 1
    - 14
- - - 2
    - 16
  - - 1
    - 16
- - - 2
    - 17
  - - 1
    - 17
- - - 3
    - 4
  - - 2
    - 4
- - - 3
    - 6
  - - 2
    - 6
- - - 3
    - 7
  - - 3
    - 6
- - - 3
    - 8
  - - 2
    - 8
- - - 3
    - 9
  - - 2
    - 9
- - - 3
    - 13
  - - 3
    - 12
- - - 3
    - 17
  - - 3
    - 16
- - - 3
    - 18
  - - 3
    - 17
- - - 4
    - 1
  - - 4
    - 0
- - - 4
    - 3
  - - 3
    - 3
- - - 4
    - 7
  - - 3
    - 7
- - - 4
    - 8
  - - 4
    - 7
- - - 4
    - 12
  - - 4
    - 11
- - - 4
    - 14
  - - 3
    - 14
- - - 4
    - 18
  - - 4
    - 17
- - - 5
    - 2
  - - 4
    - 2
- - - 5
    - 4
  - - 5
    - 3
- - - 5
    - 6
  - - 5
    - 5
- - - 5
    - 7
  - - 4
    - 7
- - - 5
    - 9
  - - 4
    - 9
- - - 5
    - 10
  - - 4
    - 10
- - - 5
    - 12
  - - 5
    - 11
- - - 5
    - 14
  - - 5
    - 13
- - - 5
    - 17
  - - 4
    - 17
- - - 5
    - 18
  - - 5
    - 17
- - - 6
    - 3
  - - 5
    - 3
- - - 6
    - 4
  - - 6
    - 3
- - - 6
    - 10
  - - 6
    - 9
- - - 6
    - 11
  - - 6
    - 10
- - - 6
    - 14
  - - 6
    - 13
- - - 6
    - 17
  - - 5
    - 17
- - - 7
    - 1
  - - 6
    - 1
- - - 7
    - 2
  - - 6
    - 2
- - - 7
    - 4
  - - 7
    - 3
- - - 7
    - 7
  - - 6
    - 7
- - - 7
    - 8
  - - 6
    - 8
- - - 7
    - 10
  - - 6
    - 10
- - - 7
    - 13
  - - 6
    - 13
- - - 7
    - 16
  - - 7
    - 15
- - - 8
    - 1
  - - 7
    - 1
- - - 8
    - 4
  - - 7
    - 4
- - - 8
    - 5
  - - 7
    - 5
- - - 8
    - 6
  - - 8
    - 5
- - - 8
    - 7
  - - 7
    - 7
- - - 8
    - 8
  - - 8
    - 7
- - - 8
    - 9
  - - 7
    - 9
- - - 8
    - 11
  - - 8
    - 10
- - - 8
    - 15
  - - 7
    - 15
- - - 9
    - 3
  - - 9
    - 2
- - - 9
    - 6
  - - 9
    - 5
- - - 9
    - 7
  - - 9
    - 6
- - - 9
    - 12
  - - 8
    - 12
- - - 9
    - 14
  - - 9
    - 13
- - - 9
    - 16
  - - 9
    - 15
- - - 9
    - 17
  - - 9
    - 16
- - - 10
    - 2
  - - 10
    - 1
- - - 10
    - 5
  - - 9
    - 5
- - - 10
    - 12
  - - 10
    - 11
- - - 10
    - 15
  - - 10
    - 14
- - - 11
    - 1
  - - 11
    - 0
- - - 11
    - 3
  - - 11
    - 2
- - - 11
    - 4
  - - 11
    - 3
- - - 11
    - 5
  - - 11
    - 4
- - - 11
    - 6
  - - 11
    - 5
- - - 11
    - 7
  - - 10
    - 7
- - - 11
    - 8
  - - 10
    - 8
- - - 11
    - 10
  - - 10
    - 10
- - - 11
    - 16
  - - 11
    - 15
- - - 11
    - 18
  - - 11
    - 17
- - - 12
    - 2
  - - 12
    - 1
- - - 12
    - 5
  - - 12
    - 4
- - - 12
    - 13
  - - 12
    - 12
- - - 12
    - 14
  - - 12
    - 13
- - - 12
    - 15
  - - 11
    - 15
- - - 13
    - 1
  - - 12
    - 1
- - - 13
    - 2
  - - 12
    - 2
- - - 13
    - 3
  - - 13
    - 2
- - - 13
    - 4
  - - 13
    - 3
- - - 13
    - 6
  - - 12
    - 6
- - - 13
    - 7
  - - 13
    - 6
- - - 13
    - 10
  - - 12
    - 10
- - - 13
    - 18
  - - 12
    - 18
- - - 14
    - 4
  - - 13
    - 4
- - - 14
    - 5
  - - 14
    - 4
- - - 14
    - 13
  - - 13
    - 13
- - - 14
    - 16
  - - 13
    - 16
- - - 14
    - 18
  - - 13
    - 18
- - - 15
    - 4
  - - 15
    - 3
- - - 15
    - 6
  - - 14
    - 6
- - - 15
    - 7
  - - 15
    - 6
- - - 15
    - 9
  - - 15
    - 8
- - - 15
    - 11
  - - 15
    - 10
- - - 15
    - 12
  - - 15
    - 11
- - - 15
    - 18
  - - 15
    - 17
- - - 16
    - 1
  - - 16
    - 0
- - - 16
    - 3
  - - 15
    - 3
- - - 16
    - 5
  - - 15
    - 5
- - - 16
    - 6
  - - 15
    - 6
- - - 16
    - 11
  - - 16
    - 10
- - - 16
    - 12
  - - 15
    - 12
- - - 16
    - 14
  - - 15
    - 14
- - - 16
    - 16
  - - 15
    - 16
- - - 17
    - 4
  - - 16
    - 4
- - - 17
    - 5
  - - 16
    - 5
- - - 17
    - 6
  - - 16
    - 6
- - - 17
    - 7
  - - 16
    - 7
- - - 17
    - 8
  - - 17
    - 7
- - - 17
    - 9
  - - 17
    - 8
- - - 17
    - 12
  - - 17
    - 11
- - - 17
    - 16
  - - 16
    - 16
- - - 17
    - 18
  - - 16
    - 18
- - - 18
    - 3
  - - 18
    - 2
- - - 18
    - 8
  - - 17
    - 8
- - - 18
    - 11
  - - 18
    - 10
- - - 18
    - 16
  - - 18
    - 15
