bumps:
  points:
  - - - 1
      - 1
    - - 0
      - 1
  - - - 1
      - 1
    - - 1
      - 0
  - - - 1
      - 48
    - - 1
      - 49
  - - - 1
      - 48
    - - 0
      - 48
  - - - 48
      - 1
    - - 48
      - 0
  - - - 49
      - 1
    - - 48
      - 1
  - - - 48
      - 49
    - - 48
      - 48
  - - - 49
      - 48
    - - 48
      - 48
